version: 2
jobs:
  code_analyze:
    docker:
      - image: circleci/openjdk:8
    steps:
      - run:
          name: Clone repository
          command: git clone https://bitbucket.org/devops_sysops/docker-apache.git
      - run:
          name: Build docker image
          command: docker build -t spy86/jboss-wildfly:$CIRCLE_SHA1 .
      - run:
          name: Login into Docker Hub
          command: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run:
          name: Push docker image to Docker Hub
          command: docker push spy86/jboss-wildfly:$CIRCLE_SHA1
workflows:
  version: 2
  test:
    jobs:
      - code_analyze